language: python

sudo: enabled

python:

    - "3.5"

env:

    global:

     - TRAVIS=true



install:

    - pip install -r requirements.txt



script:

    python classifier.py --vocab_path models/google_vocab.txt --train_path datasets/chnsenticorp/train.tsv --dev_path datasets/chnsenticorp/dev.tsv --test_path datasets/chnsenticorp/test.tsv --epochs_num 3 --batch_size 32 --encoder bert
